tables:
  t_order: 
    actualTables: t_order_${0..1}
    tableStrategy:
      shardingColumns: order_id
      algorithmExpression: t_order_${order_id.longValue() % 2}
        
  t_order_item:
    actualTables: t_order_item_${0..1}
    #绑定表中其余的表的策略与第一张表的策略相同
    tableStrategy: 
      shardingColumns: order_id
      algorithmExpression: t_order_item_${order_id.longValue() % 2}  

bindingTables:
  - tableNames: t_order,t_order_item
  
#默认数据库分片策略
defaultDatabaseStrategy:
  shardingColumns: user_id
  algorithmExpression: ds_${user_id.longValue() % 2}

props:
  metrics.enable: false