sudo: required
cache: 
  directories: 
    - "$HOME/.m2"

language: java
jdk:
#  - oraclejdk8
#  - oraclejdk7
  - openjdk8

before_script:
  - echo "MAVEN_OPTS='-Xmx1024m -XX:MaxPermSize=256m'" > ~/.mavenrc
script:
  - mvn clean install -Dmaven.javadoc.skip=true

install: travis_wait 30 mvn install --quiet
