language: java
jdk:
  - openjdk8

install: true

cache:
  directories:
    - "$HOME/.m2"

before_script:
  - echo "MAVEN_OPTS='-Xmx1024m -XX:MaxMetaspaceSize=256m'" > ~/.mavenrc

script:
  - travis_wait 30 ./mvnw --batch-mode --no-transfer-progress clean install cobertura:cobertura -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"
