baseURL = "https://shardingsphere.apache.org/blog/"
canonifyurls = true
languageCode = "en-us"
title = "ShardingSphere"
theme = "hugo-theme-learn"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "ShardingSphere"
weight = 1
languageName = "English"

[Languages.cn]
title = "ShardingSphere"
weight = 2
languageName = "Chinese"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "black"
  # Disable search function. It will hide search bar
  disableSearch = true
