##################      ##################
# Here you can configure the rules for the proxy.
#
# We provide two kinds of configurations for example. The one is the configuration of Sharding rule,
# and the other is the configuration of master-slave rule.
# If you want to use Sharding, please refer to the first one, and if you only want to use master-slave,
# please refer to the second one.
#
##################      ##################


##################
#
# The example of Sharding rule.
#
#dataSources:
#  demo_ds_0:
#    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0
#    username: root
#    password:
#  demo_ds_1:
#    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1
#    username: root
#    password:
#
#shardingRule:
#  tables:
#    t_order:
#      actualDataNodes: demo_ds_${0..1}.t_order_${0..1}
#      tableStrategy:
#        inline:
#          shardingColumn: order_id
#          algorithmExpression: t_order_${order_id % 2}
#      keyGeneratorColumnName: order_id
#    t_order_item:
#      actualDataNodes: demo_ds_${0..1}.t_order_item_${0..1}
#      tableStrategy:
#        inline:
#          shardingColumn: order_id
#          algorithmExpression: t_order_item_${order_id % 2}
#  bindingTables:
#    - t_order,t_order_item
#  defaultDatabaseStrategy:
#    inline:
#      shardingColumn: user_id
#      algorithmExpression: demo_ds_${user_id % 2}
#  defaultTableStrategy:
#    none:
#  defaultKeyGeneratorClassName: io.shardingjdbc.core.keygen.DefaultKeyGenerator
#
#  props:
#    sql.show: true


##################
#
# The example of master-slave rule.
#
#dataSources:
#  demo_ds_0:
#    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0
#    username: root
#    password:
#  demo_ds_1:
#    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1
#    username: root
#    password:
#masterSlaveRule:
#  name: ds_ms
#  masterDataSourceName: demo_ds_0
#  slaveDataSourceNames:
#    - demo_ds_1
#
