#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Issue Automation

on:
  schedule:
    - cron: '0 16 */1 * *'  # once a day
  issue_comment:
    types: [created,edited]
  issues:
    types: [labeled,reopened]

jobs:
  comment-action:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'apache/shardingsphere' && github.event_name == 'issue_comment' }}
    steps:
      - name: Trigger the CI workflow
        if: ${{ contains( github.event.comment.body , '/run ci') }} 
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repo: shardingsphere
          owner: ${{ github.actor }}
          event_type: ci-completed
  remove-inactive:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'apache/shardingsphere' && github.event_name == 'issues' && github.event.action == 'reopened' }}
    steps:
    - name: Remove "status:inactive" label
      if: ${{ contains( github.event.issue.labels.*.name , format('status{0} inactive', ':') ) }}
      uses: actions-cool/issues-helper@v2.2.1
      with:
        actions: 'remove-labels'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        labels: "status: inactive"
  check-inactive-issue:
    runs-on: ubuntu-latest
    concurrency: check-inactive  # singleton-run-stage
    if: ${{ github.repository == 'apache/shardingsphere' && github.event_name == 'schedule' }}
    steps:
      - name: Check inactive   # add `status: inactive` label
        uses: actions-cool/issues-helper@v2.2.1 
        with: 
          actions: 'check-inactive' 
          token: ${{ secrets.GITHUB_TOKEN }} 
          inactive-day: 15
          inactive-label: "status: inactive"
          body: |
            Hello ${{ github.event.issue.user.login }}, this issue has not received a reply for several days.
            This issue is supposed to be closed.
          contents: "heart"
  close-issue:
    runs-on: ubuntu-latest
    concurrency:    # singleton-run-stage
      group: close-issue
      cancel-in-progress: true
    if: ${{ github.repository == 'apache/shardingsphere' && github.event_name == 'schedule' || ( github.repository == 'apache/shardingsphere' && github.event_name == 'issues' && github.event.action == 'labeled' ) }}
    steps:
      - name: Close Issue   # close issues with `labels`
        uses: actions-cool/issues-helper@v2.2.1
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'status: inactive'
