#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Scaling Integration Test

on:
  push:
    branches: [ master, dev ]
    paths:
      - '.github/workflows/it-scaling.yml'
      - 'shardingsphere-infra/shardingsphere-infra-common/src/main/**/datasource/**'
      - 'shardingsphere-kernel/shardingsphere-data-pipeline/**'
      - 'shardingsphere-kernel/shardingsphere-data-pipeline/**/src/test/**'
      - 'shardingsphere-features/**/src/main/**/scaling/**'
      - 'shardingsphere-features/**/src/main/**/sharding/schedule/**'
      - 'shardingsphere-features/**/src/main/resources/META-INF/services/*.data.pipeline.*'
      - 'shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/**/*Pipeline*.java'
      - 'shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/resources/META-INF/services/*.data.pipeline.*'
      - '!shardingsphere-test/**'
      - 'shardingsphere-test/shardingsphere-integration-test/**'
      - '!shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/**'
      - '!*.md'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/it-scaling.yml'
      - 'shardingsphere-infra/shardingsphere-infra-common/src/main/**/datasource/**'
      - 'shardingsphere-kernel/shardingsphere-data-pipeline/**'
      - 'shardingsphere-kernel/shardingsphere-data-pipeline/**/src/test/**'
      - 'shardingsphere-features/**/src/main/**/scaling/**'
      - 'shardingsphere-features/**/src/main/**/sharding/schedule/**'
      - 'shardingsphere-features/**/src/main/resources/META-INF/services/*.data.pipeline.*'
      - 'shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/java/**/*Pipeline*.java'
      - 'shardingsphere-jdbc/shardingsphere-jdbc-core/src/main/resources/META-INF/services/*.data.pipeline.*'
      - '!shardingsphere-test/**'
      - 'shardingsphere-test/shardingsphere-integration-test/**'
      - '!shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/**'
      - '!*.md'
  schedule:
    - cron: '0 22 */1 * *'  # once a day. UTC time

concurrency:
  group: it-scaling-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.javadoc.skip=true -Drat.skip=true -Dcheckstyle.skip=true -Djacoco.skip=true

jobs:
  build-it-image:
    name: build-it-image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Maven resolve ranges
        run: ./mvnw versions:resolve-ranges -ntp -Dincludes='org.springframework:*,org.springframework.boot:*'
      - name: Cache Maven Repos
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-it-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build IT image
        run: ./mvnw -B clean install -am -pl shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling -Pit.env.docker -DskipTests
      - name: Save IT image
        run: docker save -o /tmp/shardingsphere-proxy-test.tar apache/shardingsphere-proxy-test:latest
      - name: Upload IT image
        uses: actions/upload-artifact@v3
        with:
          name: it-image
          path: /tmp/shardingsphere-proxy-test.tar
  
  mysql-it-test:
    if: (github.event_name != 'schedule' && github.repository == 'apache/shardingsphere')
    name: mysql-it-test
    runs-on: ubuntu-latest
    env:
      mysql_version: mysql:5.7
    timeout-minutes: 30
    needs: build-it-image
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven Repos
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-it-cache-${{ github.sha }}
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/pom.xml -Dcheckstyle.skip=true -Dit.cluster.env.type=DOCKER -Dit.env.mysql.version=${{ env.mysql_version }} -Dit.env.postgresql.version=
  
  postgresql-it-test:
    if: (github.event_name != 'schedule' && github.repository == 'apache/shardingsphere')
    name: postgres-it-test
    runs-on: ubuntu-latest
    env:
      postgresql_version: postgres:12-alpine
    timeout-minutes: 30
    needs: build-it-image
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven Repos
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-it-cache-${{ github.sha }}
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/pom.xml -Dcheckstyle.skip=true -Dit.cluster.env.type=DOCKER -Dit.env.postgresql.version=${{ env.postgresql_version }} -Dit.env.mysql.version=
  
  daily-it-test:
    if: (github.event_name == 'schedule' && github.repository == 'apache/shardingsphere')
    name: daily-it-test
    runs-on: ubuntu-latest
    env:
      postgresql_version: postgres:10-alpine,postgres:11-alpine,postgres:12-alpine,postgres:13-alpine,postgres:14-alpine
      mysql_version: mysql:5.7,mysql:8.0
    timeout-minutes: 60
    needs: build-it-image
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven Repos
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-it-cache-${{ github.sha }}
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-scaling/pom.xml -Dcheckstyle.skip=true -Dit.cluster.env.type=DOCKER -Dit.env.postgresql.version=${{ env.postgresql_version }} -Dit.env.mysql.version=${{ env.mysql_version }}
