#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Integration Test

on:
  push:
    branches: [ master, dev ]
    paths:
      - '.github/workflows/**'
      - '**/src/main/**'
      - '!examples/**'
      - '!shardingsphere-distribution/**'
      - '!shardingsphere-kernel/shardingsphere-data-pipeline/**'
      - '!shardingsphere-test/**'
      - 'shardingsphere-test/shardingsphere-integration-test/**'
      - 'shardingsphere-test/shardingsphere-integration-agent-test/**'
      - '!*.md'
      - '!*.txt'
      - '!.*.yaml'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - '**/src/main/**'
      - '!examples/**'
      - '!shardingsphere-distribution/**'
      - '!shardingsphere-kernel/shardingsphere-data-pipeline/**'
      - '!shardingsphere-test/**'
      - 'shardingsphere-test/shardingsphere-integration-test/**'
      - 'shardingsphere-test/shardingsphere-integration-agent-test/**'
      - '!*.md'
      - '!*.txt'
      - '!.*.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.javadoc.skip=true -Drat.skip=true -Djacoco.skip=true -Dcheckstyle.skip=true

jobs:
  build-it-image:
    name: build-it-image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: shardingsphere-it-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build IT image
        run: ./mvnw -B clean install -am -pl shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite -Pit.env.docker -DskipTests
      - name: Save IT image
        run: docker save -o /tmp/shardingsphere-proxy-test.tar apache/shardingsphere-proxy-test:latest
      - name: Upload IT image
        uses: actions/upload-artifact@v3
        with: 
          name: it-image
          path: /tmp/shardingsphere-proxy-test.tar
  
  it-empty-rule:
    name: empty rule
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-it-image
    strategy:
      matrix:
        env: [ docker ]
        adapter: [ proxy, jdbc ]
        database: [ MySQL, PostgreSQL ]
        scenario: [ empty_rules ]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: shardingsphere-it-cache-${{ github.sha }}
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        if: matrix.adapter == 'proxy'
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/pom.xml -Dit.run.modes=Cluster -Dit.scenarios=${{ matrix.scenario }} -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.cluster.databases=${{ matrix.database }} -Dit.cluster.env.type=DOCKER
  
  it-single-rule:
    name: single rule
    needs: it-empty-rule
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        env: [ docker ]
        adapter: [ proxy, jdbc ]
        database: [ MySQL, PostgreSQL ]
        scenario: [ db, tbl, encrypt, readwrite_splitting, shadow ]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: shardingsphere-it-cache-${{ github.sha }}
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        if: matrix.adapter == 'proxy'
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/pom.xml -Dit.run.modes=Cluster -Dit.scenarios=${{ matrix.scenario }} -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.culster.databases=${{ matrix.database }} -Dit.cluster.env.type=DOCKER
  
  it-mixture-rule:
    name: mixture rule
    needs: [ it-empty-rule, it-single-rule ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        env: [ docker ]
        adapter: [ proxy, jdbc ]
        database: [ MySQL, PostgreSQL ]
        scenario: [ dbtbl_with_readwrite_splitting, dbtbl_with_readwrite_splitting_and_encrypt ]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: shardingsphere-it-cache-${{ github.sha }}
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        if: matrix.adapter == 'proxy'
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f shardingsphere-test/shardingsphere-integration-test/shardingsphere-integration-test-suite/pom.xml -Dit.run.modes=Cluster -Dit.scenarios=${{ matrix.scenario }} -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.cluster.databases=${{ matrix.database }} -Dit.cluster.env.type=DOCKER
  
  mysql-proxy-agent-metrics:
    name: MySQL-Proxy with Agent Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - name: Dump concurrency group
        env:
          CON_GROUP: ${{ github.workflow }}-${{ github.ref }}
        run: echo "$CON_GROUP"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build Project
        run: ./mvnw -B clean install -DskipITs -DskipTests
      - name: Run Integration Test
        run: ./mvnw -B clean install -f shardingsphere-test/shardingsphere-integration-agent-test/shardingsphere-integration-agent-test-plugins/shardingsphere-integration-agent-test-metrics/pom.xml -Pit.env.metrics
  
  mysql-proxy-agent-tracing-opentelemetry:
    name: MySQL-Proxy with Agent Tracing OpenTelemetry
    runs-on: ubuntu-latest
    steps:
      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build Project
        run: ./mvnw -B clean install -DskipITs -DskipTests
      - name: Run Integration Test
        run: ./mvnw -B clean install -f shardingsphere-test/shardingsphere-integration-agent-test/shardingsphere-integration-agent-test-plugins/shardingsphere-integration-agent-test-opentelemetry/pom.xml -Pit.env.opentelemetry
