#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: IT

on:
  push:
    branches: [ master, dev ]
#    paths:
#      - '.github/workflows/it.yml'
#      - '**/pom.xml'
#      - '**/src/main/**'
#      - 'distribution/proxy/**'
#      - 'test/pom.xml'
#      - 'test/integration-test/fixture/**'
#      - 'test/integration-test/env/**'
#      - 'test/integration-test/test-suite/**'
#      - 'test/integration-agent-test/**'
#      - '!examples/**'
#      - '!distribution/**'
#      - '!distribution/proxy/src/main/release-docs/**'
#      - '!kernel/data-pipeline/**'
#      - '!test/**'
#      - '!*.md'
  pull_request:
    branches: [ master ]
#    paths:
#      - '.github/workflows/it.yml'
#      - '**/pom.xml'
#      - '**/src/main/**'
#      - 'distribution/proxy/**'
#      - '!test/**'
#      - 'test/pom.xml'
#      - 'test/integration-test/fixture/**'
#      - 'test/integration-test/env/**'
#      - 'test/integration-test/test-suite/**'
#      - 'test/integration-agent-test/**'
#      - '!examples/**'
#      - '!distribution/**'
#      - '!distribution/proxy/src/main/release-docs/**'
#      - '!kernel/data-pipeline/**'
#      - '!*.md'

concurrency:
  group: it-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Djacoco.skip=true -Dspotless.apply.skip=true

jobs:
  build-it-image:
    name: Build IT image
    runs-on: ubuntu-latest
#     continue-on-error: ${{ matrix.experimental}}
    continue-on-error: true
    strategy:
#       fail-fast: true
      matrix:
        java: ['8','11','17','19']
        keyword: ['temurin','zulu','adopt','adopt-openj9','liberica','microsoft','corretto']
#         experimental: [false]
#         include:
#           - java: 19
#             keyword: adopt-openj9 
#             experimental: true
#           - java: 19
#             keyword: microsoft
#             experimental: true
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.keyword }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-it-cache-${{ github.sha }}
          restore-keys: |
            shardingsphere-maven-third-party-it-cache-
            shardingsphere-maven-third-party-
      - name: Maven resolve ranges
        run: ./mvnw versions:resolve-ranges -ntp -Dincludes='org.springframework:*,org.springframework.boot:*'
      - name: Build IT image
        run: ./mvnw -B clean install -am -pl test/integration-test/test-suite -Pit.env.docker -DskipTests -Dspotless.apply.skip=true
      - name: Verify Suite CI Run
        run: ./mvnw -B install -pl test/integration-test/test-suite -Dspotless.apply.skip=true
      - name: Save IT image
        run: docker save -o /tmp/shardingsphere-proxy-test.tar apache/shardingsphere-proxy-test:latest
      - uses: actions/upload-artifact@v3
        with:
          name: it-image
          path: /tmp/shardingsphere-proxy-test.tar
          retention-days: 1

  it-empty-rule:
    name: empty rule
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-it-image
    strategy:
      matrix:
        adapter: [ proxy, jdbc ]
        database: [ MySQL, PostgreSQL, openGauss ]
        scenario: [ empty_rules, rdl_empty_rules ]
        java: ['8','11','17','19']
        keyword: ['temurin','zulu','adopt','adopt-openj9','liberica','microsoft','corretto']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-it-cache-${{ github.sha }}
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.keyword }}
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        if: matrix.adapter == 'proxy'
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f test/integration-test/test-suite/pom.xml -Dspotless.apply.skip=true -Dit.run.modes=Cluster -Dit.scenarios=${{ matrix.scenario }} -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.cluster.databases=${{ matrix.database }} -Dit.cluster.env.type=DOCKER

  it-single-rule:
    name: single rule
    needs: it-empty-rule
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      max-parallel: 10
      matrix:
        adapter: [ proxy, jdbc ]
        mode: [ Standalone, Cluster ]
        database: [ MySQL, PostgreSQL, openGauss ]
        scenario: [ db, tbl, encrypt, readwrite_splitting, shadow ]
        java: ['8','11','17','19']
        keyword: ['temurin','zulu','adopt','adopt-openj9','liberica','microsoft','corretto']
        exclude:
          - adapter: jdbc
            mode: Cluster
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-it-cache-${{ github.sha }}
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.keyword }}
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        if: matrix.adapter == 'proxy'
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f test/integration-test/test-suite/pom.xml -Dspotless.apply.skip=true -Dit.cluster.env.type=DOCKER -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.run.modes=${{ matrix.mode }} -Dit.cluster.databases=${{ matrix.database }} -Dit.scenarios=${{ matrix.scenario }}

  it-mixture-rule:
    name: mixture rule
    needs: it-single-rule
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      max-parallel: 8
      matrix:
        java: ['8','11','17','19']
        keyword: ['temurin','zulu','adopt','adopt-openj9','liberica','microsoft','corretto']
        adapter: [ proxy, jdbc ]
        mode: [ Standalone, Cluster ]
        database: [ MySQL, PostgreSQL, openGauss ]
        scenario: [ dbtbl_with_readwrite_splitting, dbtbl_with_readwrite_splitting_and_encrypt, sharding_and_encrypt, encrypt_and_readwrite_splitting, encrypt_shadow, readwrite_splitting_and_shadow, sharding_and_shadow, sharding_encrypt_shadow ]
        exclude:
          - adapter: jdbc
            mode: Cluster
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-it-cache-${{ github.sha }}
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.keyword }}
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        uses: actions/download-artifact@v3
        with:
          name: it-image
          path: /tmp/
      - name: Load IT image
        if: matrix.adapter == 'proxy'
        run: docker load -i /tmp/shardingsphere-proxy-test.tar
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f test/integration-test/test-suite/pom.xml -Dspotless.apply.skip=true -Dit.cluster.env.type=DOCKER -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.run.modes=${{ matrix.mode }} -Dit.cluster.databases=${{ matrix.database }} -Dit.scenarios=${{ matrix.scenario }}

  mysql-proxy-agent:
    name: Agent Metrics & OpenTelemetry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8','11','17','19']
        keyword: ['temurin','zulu','adopt','adopt-openj9','liberica','microsoft','corretto']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.keyword }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            shardingsphere-maven-third-party-
      - name: Maven resolve ranges
        run: ./mvnw versions:resolve-ranges -ntp -Dincludes='org.springframework:*,org.springframework.boot:*'
      - name: Build Project
        run: ./mvnw -B clean install -DskipITs -DskipTests
      - name: Run Integration Test
        run: |
          ./mvnw -B clean install -f test/integration-agent-test/plugins/metrics/pom.xml -Dspotless.apply.skip=true -Pit.env.metrics
          ./mvnw -B clean install -f test/integration-agent-test/plugins/opentelemetry/pom.xml -Dspotless.apply.skip=true -Pit.env.opentelemetry
