#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: IT

on:
  push:
  workflow_dispatch:

concurrency:
  group: it-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -Djacoco.skip=true -Dspotless.apply.skip=true -Drat.skip=true
  HUB: ghcr.io/apache/shardingsphere
  PROXY: ghcr.io/apache/shardingsphere-proxy

jobs:
  build-it-image:
    name: Build IT image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-it-cache-${{ github.sha }}
          restore-keys: |
            shardingsphere-maven-third-party-it-cache-
            shardingsphere-maven-third-party-
      - name: Maven resolve ranges
        run: ./mvnw versions:resolve-ranges -ntp -Dincludes='org.springframework:*,org.springframework.boot:*'
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: ./mvnw -B -Prelease,docker -DskipTests -Dproxy.image.repository=${{ env.PROXY }} -Dproxy.image.tag=${{ github.sha }} clean install
      - name: Push docker image
        run: docker push ${{ env.PROXY }}:${{ github.sha }}
        
  it-empty-rule:
    name: empty rule
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-it-image
    strategy:
      matrix:
        adapter: [ proxy, jdbc ]
        database: [ MySQL, PostgreSQL, openGauss ]
        scenario: [ empty_rules, rdl_empty_rules ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-it-cache-${{ github.sha }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        run: docker pull ${{ env.PROXY }}:${{ github.sha }}
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f test/integration-test/test-suite/pom.xml -Dspotless.apply.skip=true -Dit.run.modes=Cluster -Dit.scenarios=${{ matrix.scenario }} -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.cluster.databases=${{ matrix.database }} -Dit.cluster.env.type=DOCKER

  it-single-rule:
    name: single rule
    needs: it-empty-rule
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        adapter: [ proxy, jdbc ]
        mode: [ Standalone, Cluster ]
        database: [ MySQL, PostgreSQL, openGauss ]
        scenario: [ db, tbl, encrypt, readwrite_splitting, shadow ]
        exclude:
          - adapter: jdbc
            mode: Cluster
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-it-cache-${{ github.sha }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        run: docker pull ${{ env.PROXY }}:${{ github.sha }}
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f test/integration-test/test-suite/pom.xml -Dspotless.apply.skip=true -Dit.cluster.env.type=DOCKER -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.run.modes=${{ matrix.mode }} -Dit.cluster.databases=${{ matrix.database }} -Dit.scenarios=${{ matrix.scenario }}

  it-mixture-rule:
    name: mixture rule
    needs: it-single-rule
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        adapter: [ proxy, jdbc ]
        mode: [ Standalone, Cluster ]
        database: [ MySQL, PostgreSQL, openGauss ]
        scenario: [ dbtbl_with_readwrite_splitting, dbtbl_with_readwrite_splitting_and_encrypt, sharding_and_encrypt, encrypt_and_readwrite_splitting, encrypt_shadow, readwrite_splitting_and_shadow, sharding_and_shadow, sharding_encrypt_shadow ]
        exclude:
          - adapter: jdbc
            mode: Cluster
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-it-cache-${{ github.sha }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Download IT image
        if: matrix.adapter == 'proxy'
        run: docker pull ${{ env.PROXY }}:${{ github.sha }}
      - name: Run Integration Test
        run: ./mvnw -nsu -B install -f test/integration-test/test-suite/pom.xml -Dspotless.apply.skip=true -Dit.cluster.env.type=DOCKER -Dit.cluster.adapters=${{ matrix.adapter }} -Dit.run.modes=${{ matrix.mode }} -Dit.cluster.databases=${{ matrix.database }} -Dit.scenarios=${{ matrix.scenario }}

  mysql-proxy-agent:
    name: Agent Metrics & OpenTelemetry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: shardingsphere-maven-third-party-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            shardingsphere-maven-third-party-
      - name: Maven resolve ranges
        run: ./mvnw versions:resolve-ranges -ntp -Dincludes='org.springframework:*,org.springframework.boot:*'
      - name: Build Project
        run: ./mvnw -B clean install -DskipITs -DskipTests
      - name: Run Integration Test
        run: |
          ./mvnw -B clean install -f test/integration-agent-test/plugins/metrics/pom.xml -Dspotless.apply.skip=true -Pit.env.metrics
          ./mvnw -B clean install -f test/integration-agent-test/plugins/opentelemetry/pom.xml -Dspotless.apply.skip=true -Pit.env.opentelemetry
